### PR TITLE
in progress: check for unguarded type vars

### PR DESCRIPTION
**Pull request by bennn**
Q. how to report source locations?

Q. where to put `removeAll`?

### CODE REVIEW

**Comment by mflatt** [comment]
For the error, I'd use `synatx_meta.error` and just pick one of the elements to complain about. The enclosing form could be passed to `poly_ize_upto` for the error.

**Comment by bennn** [comment]
better now!

Screenshot 2023-09-02 at 8 40 14 AM

**Comment by mflatt** [comment]
This is better, but I still question showing a list of types in the error message. Part of my rservation is that error-message content shouldn't use the printed form of language-level values except where it's showing values produced in the program; that's more a guideline than a rule, though. More significantly, note that `?_a` happens to look like `?a`, but if you write `?z` and `?x` in the source program, the printed list of type variables is still `["?_a", "?_b"]`.

**Comment by bennn** [comment]
Oh! ?z vs ?_a is really bad.

Changed to not print variables.

**Comment by mflatt** [comment]
Ok! I think the only other thing is to update the docs in `shplait.scrbl` (around line 165).

**Comment by bennn** [comment]
ready to squash and merge?

**Comment by mflatt** [comment]
Yes, LGTM

**Pull request merged**
